null
{ region: 
   { span: 
      { latitude_delta: 0.0057629185664609395,
        longitude_delta: 0.013087601928504 },
     center: { latitude: 37.3736424915607, longitude: -122.0360979099675 } },
  total: 10835,
  businesses: 
   [ { is_claimed: true,
       rating: 4.5,
       mobile_url: 'http://m.yelp.com/biz/dishdash-sunnyvale',
       rating_img_url: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png',
       review_count: 2200,
       name: 'DishDash',
       snippet_image_url: 'http://s3-media3.ak.yelpcdn.com/photo/crT8fKNW7WnQJBTLsC3O1A/ms.jpg',
       rating_img_url_small: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png',
       url: 'http://www.yelp.com/biz/dishdash-sunnyvale',
       menu_date_updated: 1387608734,
       phone: '4087741889',
       snippet_text: 'One of my favorite Mediterranean spots all time in the Bay Area. Every time I try a new dish here it becomes one of my comfort foods. Not yet a single...',
       image_url: 'http://s3-media3.ak.yelpcdn.com/bphoto/YZuhZsHC8alkVb47MZMUgg/ms.jpg',
       categories: [Object],
       display_phone: '+1-408-774-1889',
       rating_img_url_large: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/9f83790ff7f6/ico/stars/v1/stars_large_4_half.png',
       menu_provider: 'single_platform',
       id: 'dishdash-sunnyvale',
       is_closed: false,
       location: [Object] },
     { is_claimed: true,
       rating: 4,
       mobile_url: 'http://m.yelp.com/biz/kabul-sunnyvale',
       rating_img_url: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/c2f3dd9799a5/ico/stars/v1/stars_4.png',
       review_count: 595,
       name: 'Kabul',
       snippet_image_url: 'http://s3-media1.ak.yelpcdn.com/photo/HKfDF-2p3Fiig274rWdX9Q/ms.jpg',
       rating_img_url_small: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/f62a5be2f902/ico/stars/v1/stars_small_4.png',
       url: 'http://www.yelp.com/biz/kabul-sunnyvale',
       menu_date_updated: 1392977043,
       phone: '4082454350',
       snippet_text: 'This restaurant is awesome!\nI always wanted to try this place but never really got around to it. Now I wish I would have come sooner because it was soooo...',
       image_url: 'http://s3-media4.ak.yelpcdn.com/bphoto/Ajat7A4uF0nMXEI37-GUmw/ms.jpg',
       categories: [Object],
       display_phone: '+1-408-245-4350',
       rating_img_url_large: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/ccf2b76faa2c/ico/stars/v1/stars_large_4.png',
       menu_provider: 'single_platform',
       id: 'kabul-sunnyvale',
       is_closed: false,
       location: [Object] } ] }

[ { is_claimed: false,
    rating: 2,
    mobile_url: 'http://m.yelp.com/biz/advanced-cardiovascular-specialists-mountain-view-2',
    rating_img_url: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/b561c24f8341/ico/stars/v1/stars_2.png',
    review_count: 6,
    name: 'Advanced Cardiovascular Specialists',
    snippet_image_url: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/cc4afe21892e/default_avatars/user_medium_square.png',
    rating_img_url_small: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/a6210baec261/ico/stars/v1/stars_small_2.png',
    url: 'http://www.yelp.com/biz/advanced-cardiovascular-specialists-mountain-view-2',
    phone: '6509624690',
    snippet_text: 'Both my husband and I have been patients of Dr. Catherine Collings for more than 13 years. Dr. Collings is great. She\'s compassionate, caring, taking the...',
    categories: [Object],
    display_phone: '+1-650-962-4690',
    rating_img_url_large: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/c00926ee5dcb/ico/stars/v1/stars_large_2.png',
    id: 'advanced-cardiovascular-specialists-mountain-view-2',
    is_closed: false,
    location: [Object] } ] }

{ is_claimed: true,
	  rating: 2.5,
	  mobile_url: 'http://m.yelp.com/biz/yelp-san-francisco',
	  rating_img_url: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/c7fb9aff59f9/ico/stars/v1/stars_2_half.png',
	  review_count: 5858,
	  name: 'Yelp',
	  snippet_image_url: 'http://s3-media4.ak.yelpcdn.com/photo/p64MNia3_pjIsVCVBaRzgw/ms.jpg',
	  rating_img_url_small: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/8e8633e5f8f0/ico/stars/v1/stars_small_2_half.png',
	  url: 'http://www.yelp.com/biz/yelp-san-francisco',
	  reviews: 
	   [ { rating: 5,
	       excerpt: 'Dedicated to all my Yelpers, be on the lookout this year for my Song Video Blog\n\nSong parody of Warren G\'s 1994 song "This...',
	       time_created: 1397024745,
	       rating_image_url: 'http://s3-media1.ak.yelpcdn.com/assets/2/www/img/f1def11e4e79/ico/stars/v1/stars_5.png',
	       rating_image_small_url: 'http://s3-media1.ak.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png',
	       user: [Object],
	       rating_image_large_url: 'http://s3-media3.ak.yelpcdn.com/assets/2/www/img/22affc4e6c38/ico/stars/v1/stars_large_5.png',
	       id: 'eJG4tQDtayViI20nY0eYgQ' } ],
	  phone: '4159083801',
	  snippet_text: 'I think I\'m addicted to this site just a few seconds into it. Fun to give my thoughts on the places near me.\n\nI understand there are lot of problems with it...',
	  image_url: 'http://s3-media3.ak.yelpcdn.com/bphoto/4LSTYqXkQ-YrI1CQmr2dQA/ms.jpg',
	  categories: 
	   [ [ 'Local Flavor', 'localflavor' ],
	     [ 'Mass Media', 'massmedia' ] ],
	  display_phone: '+1-415-908-3801',
	  rating_img_url_large: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/d63e3add9901/ico/stars/v1/stars_large_2_half.png',
	  id: 'yelp-san-francisco',
	  is_closed: false,
	  location: 
	   { cross_streets: 'Natoma St & Minna St',
	     city: 'San Francisco',
	     display_address: 
	      [ '140 New Montgomery St',
	        '(b/t Natoma St & Minna St)',
	        'Financial District',
	        'San Francisco, CA 94105' ],
	     neighborhoods: [ 'Financial District', 'SoMa' ],
	     postal_code: '94105',
	     country_code: 'US',
	     address: [ '140 New Montgomery St' ],
	     state_code: 'CA' } }

